//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Body
    {
        public int body_id { get; set; }
        public string body_title { get; set; }
        public string body_body { get; set; }
        public Nullable<int> body_version { get; set; }
    }
}
