//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cv()
        {
            this.Submits = new HashSet<Submit>();
        }
    
        public int cv_id { get; set; }
        public string cv_fullname { get; set; }
        public string cv_location { get; set; }
        public Nullable<System.DateTime> cv_bird { get; set; }
        public Nullable<int> cv_sex { get; set; }
        public string cv_phone { get; set; }
        public string cv_email { get; set; }
        public string cv_address { get; set; }
        public string cv_linkfc { get; set; }
        public string cv_target { get; set; }
        public Nullable<System.DateTime> cv_datebegineducation { get; set; }
        public Nullable<System.DateTime> cv_dateendeducation { get; set; }
        public string cv_contenteducation { get; set; }
        public Nullable<System.DateTime> cv_datebeginexp { get; set; }
        public Nullable<System.DateTime> cv_dateendexp { get; set; }
        public string cv_contentexp { get; set; }
        public Nullable<System.DateTime> cv_datebeginexptwo { get; set; }
        public Nullable<System.DateTime> cv_dateendexptwo { get; set; }
        public string cv_contentexptwo { get; set; }
        public Nullable<System.DateTime> cv_datebeginactivate { get; set; }
        public Nullable<System.DateTime> cv_dateendactivate { get; set; }
        public string cv_contentactivate { get; set; }
        public string cv_contentcertificate { get; set; }
        public string cv_contentreward { get; set; }
        public string cv_english { get; set; }
        public string cv_IT { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> cv_numbertheme { get; set; }
        public string cv_yearre { get; set; }
        public string cv_yearcerti { get; set; }
        public string cv_schools { get; set; }
        public string cv_industrystory { get; set; }
        public Nullable<int> cv_species { get; set; }
        public string cv_point { get; set; }
        public string cv_roleexp { get; set; }
        public string cv_roleexptwo { get; set; }
        public Nullable<bool> cv_activate { get; set; }
        public Nullable<bool> cv_option { get; set; }
        public Nullable<System.DateTime> cv_datecreated { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submit> Submits { get; set; }
    }
}
