//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int favourite_id { get; set; }
        public Nullable<System.DateTime> favourite_datecreate { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> favourite_delete { get; set; }
    
        public virtual User User { get; set; }
        public virtual Work Work { get; set; }
    }
}
