//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submit
    {
        public int submit_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> work_id { get; set; }
        public Nullable<System.DateTime> submit_datecreated { get; set; }
        public Nullable<int> cv_id { get; set; }
        public Nullable<bool> submit_ViewEm { get; set; }
        public Nullable<bool> submit_Check { get; set; }
    
        public virtual Cv Cv { get; set; }
        public virtual User User { get; set; }
        public virtual Work Work { get; set; }
    }
}
