//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int theme_id { get; set; }
        public Nullable<int> cv_id { get; set; }
        public Nullable<int> theme_datecreate { get; set; }
    }
}
