//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.Submits = new HashSet<Submit>();
            this.Favourites = new HashSet<Favourite>();
            this.Likes = new HashSet<Like>();
        }
    
        public int work_id { get; set; }
        public string work_name { get; set; }
        public string work_image { get; set; }
        public Nullable<System.DateTime> work_deadline { get; set; }
        public string work_description { get; set; }
        public string work_request { get; set; }
        public string work_benefit { get; set; }
        public string work_address { get; set; }
        public Nullable<int> work_moneyf { get; set; }
        public Nullable<int> work_moneye { get; set; }
        public Nullable<int> work_amount { get; set; }
        public Nullable<bool> work_activate { get; set; }
        public Nullable<bool> work_option { get; set; }
        public Nullable<int> work_view { get; set; }
        public Nullable<int> work_love { get; set; }
        public string work_map { get; set; }
        public Nullable<System.DateTime> work_datecreated { get; set; }
        public Nullable<System.DateTime> work_dateexpired { get; set; }
        public Nullable<System.DateTime> work_datesend { get; set; }
        public string work_imagetwo { get; set; }
        public string work_imgathree { get; set; }
        public Nullable<int> employer_id { get; set; }
        public Nullable<int> work_pricemin { get; set; }
        public Nullable<int> work_pricemax { get; set; }
        public string work_symbol { get; set; }
        public Nullable<int> work_sex { get; set; }
        public Nullable<bool> work_format { get; set; }
        public Nullable<int> work_yearsofexp { get; set; }
        public Nullable<int> work_province { get; set; }
        public string work_ifamemap { get; set; }
        public string work_note { get; set; }
        public Nullable<bool> work_delete { get; set; }
        public Nullable<bool> work_spam { get; set; }
        public Nullable<int> province_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> career_id { get; set; }
        public Nullable<bool> work_del { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual Form Form { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submit> Submits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Like> Likes { get; set; }
    }
}
