//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int work_id { get; set; }
        public string work_name { get; set; }
        public string work_image { get; set; }
        public Nullable<System.DateTime> work_deadline { get; set; }
        public string work_description { get; set; }
        public string work_request { get; set; }
        public string work_benefit { get; set; }
        public string work_address { get; set; }
        public Nullable<int> work_moneyf { get; set; }
        public Nullable<int> work_moneye { get; set; }
        public Nullable<int> work_amount { get; set; }
        public Nullable<bool> work_activate { get; set; }
        public Nullable<bool> work_option { get; set; }
        public Nullable<int> work_view { get; set; }
        public Nullable<int> work_love { get; set; }
        public string work_map { get; set; }
        public Nullable<System.DateTime> work_datecreated { get; set; }
        public Nullable<System.DateTime> work_dateexpired { get; set; }
        public Nullable<System.DateTime> work_datesend { get; set; }
        public string work_imagetwo { get; set; }
        public string work_imgathree { get; set; }
        public Nullable<int> employer_id { get; set; }
        public Nullable<int> work_pricemin { get; set; }
        public Nullable<int> work_pricemax { get; set; }
        public string work_symbol { get; set; }
        public Nullable<int> work_sex { get; set; }
        public Nullable<bool> work_format { get; set; }
        public Nullable<int> work_yearsofexp { get; set; }
        public Nullable<int> work_province { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
